CREATE TABLE psychiatrists (
    psychiatrists_id INT PRIMARY KEY AUTO_INCREMENT,
    psychiatrists_name VARCHAR(100) NOT NULL,
    hospital_id INT,
    FOREIGN KEY (hospital_id) REFERENCES hospitals(hospital_id)
);


INSERT INTO psychiatrists (psychiatrists_name, hospital_id) VALUES
('Dr. Kapoor', 1),
('Dr. Patel', 2),
('Dr. Sharma', 3),
('Dr. Verma', 4),
('Dr. Reddy', 1),
('Dr. Singh', 2),
('Dr. Gupta', 3),
('Dr. Malhotra', 4),
('Dr. Kumar', 1),
('Dr. Chatterjee', 2),
('Dr. Desai', 3),
('Dr. Iyer', 4),
('Dr. Saha', 1),
('Dr. Joshi', 2),
('Dr. Mishra', 3),
('Dr. Saxena', 4),
('Dr. Das', 1),
('Dr. Roy', 2),
('Dr. Nair', 3),
('Dr. Menon', 4),
('Dr. Khan', 1),
('Dr. Ahmed', 2),
('Dr. Dubey', 3),
('Dr. Thakur', 4),
('Dr. Bansal', 1),
('Dr. Agarwal', 2),
('Dr. Khanna', 3),
('Dr. Rao', 4),
('Dr. Shukla', 1),
('Dr. Sundaram', 2),
('Dr. Iyengar', 3),
('Dr. Sinha', 4),
('Dr. Rajput', 1);